### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by LOGANLEEE** [NinanoKwon/hackcovy#1]
<img width="882" alt="Screen Shot 2020-05-12 at 0 54 33" src="https://user-images.githubusercontent.com/26853553/81582628-3b514180-93eb-11ea-9ebd-0e58c2d24ae4.png">

commit 혹은 push 확인 해보셔야할것같아요~ :D

**Comment by NinanoKwon** [comment]
넵 제가 git이랑 씨름하다가 문제가 생겨서.. ㅠ 수정하도록 하겠습니다
